import React, { useState, useEffect } from 'react';
import ForgeReconciler, {
    Text,
    Button,
    Stack,
    Heading,
    SectionMessage,
    Inline,
    Badge,
    Strong
} from '@forge/react';
import { invoke, view } from '@forge/bridge';

const App = () => {
    const [loading, setLoading] = useState(true);
    const [inserting, setInserting] = useState(false);
    const [report, setReport] = useState(null);
    const [error, setError] = useState(null);
    const [inserted, setInserted] = useState(false);

    const loadReport = async () => {
        setLoading(true);
        setError(null);
        try {
            const response = await invoke('insertReportHandler');
            if (response.success) {
                setReport(response);
                if (response.inserted) {
                    setInserted(true);
                }
            } else {
                setError(response.message || 'Failed to generate report');
            }
        } catch (err) {
            setError(err.message || 'Failed to generate report');
        } finally {
            setLoading(false);
        }
    };

    const handleInsertToPage = async () => {
        setInserting(true);
        try {
            // Get context to pass content ID
            const context = await view.getContext();
            console.log('=== FRONTEND CONTEXT ===', JSON.stringify(context, null, 2));

            // Try multiple paths to get content ID
            const contentId = context?.extension?.content?.id ||
                context?.content?.id ||
                context?.contentId;

            console.log('Resolved contentId:', contentId);

            if (!contentId) {
                console.error('No contentId found in context!');
            }

            const response = await invoke('insertReportHandler', {
                contentId: contentId,
                debugContext: context
            });
            console.log('Handler response:', response);

            if (response.inserted) {
                setInserted(true);
            }
        } catch (err) {
            console.error('Insert error:', err);
        } finally {
            setInserting(false);
        }
    };

    // Auto-load on mount
    useEffect(() => {
        loadReport();
    }, []);

    if (loading) {
        return (
            <Stack space="space.200">
                <Text>Loading sprint data...</Text>
            </Stack>
        );
    }

    if (error) {
        return (
            <Stack space="space.200">
                <SectionMessage appearance="error">
                    <Text>{error}</Text>
                </SectionMessage>
                <Button onClick={loadReport}>Retry</Button>
            </Stack>
        );
    }

    if (inserted) {
        return (
            <Stack space="space.200">
                <SectionMessage appearance="success">
                    <Text>Sprint Retro Report inserted successfully!</Text>
                </SectionMessage>
                <Text>Refresh the page to see the report content.</Text>
            </Stack>
        );
    }

    if (report && report.success) {
        const metrics = report.metrics || {};
        return (
            <Stack space="space.200">
                <Heading as="h2">🏎️ Sprint Retrospective: {metrics.sprintName || 'Sprint'}</Heading>

                <SectionMessage appearance="information">
                    <Text>Generated by SprintGPT on {new Date().toLocaleDateString()}</Text>
                </SectionMessage>

                <Heading as="h3">Sprint Health Score</Heading>
                <Inline space="space.100">
                    <Badge appearance={metrics.healthScore >= 70 ? 'added' : 'removed'}>
                        {metrics.healthScore || 0}/100
                    </Badge>
                </Inline>

                <Heading as="h3">Key Metrics</Heading>
                <Stack space="space.100">
                    <Text>• <Strong>Velocity:</Strong> {metrics.velocity || 0} story points</Text>
                    <Text>• <Strong>Completion Rate:</Strong> {metrics.completionRate || 0}%</Text>
                    <Text>• <Strong>Avg Cycle Time:</Strong> {metrics.avgCycleTime || 0} days</Text>
                    <Text>• <Strong>Blocked Issues:</Strong> {metrics.blockedIssues || 0}</Text>
                </Stack>

                <Heading as="h3">Discussion Topics</Heading>
                <Stack space="space.100">
                    <Text>1. What went well this sprint?</Text>
                    <Text>2. What could we improve?</Text>
                    <Text>3. What actions should we take?</Text>
                </Stack>

                <Heading as="h3">Action Items</Heading>
                <Stack space="space.100">
                    <Text>☐ Review and address blocked items earlier</Text>
                    <Text>☐ Continue practices that maintained velocity</Text>
                </Stack>

                <Stack space="space.200">
                    <Button
                        appearance="primary"
                        onClick={handleInsertToPage}
                        isLoading={inserting}
                    >
                        {inserting ? 'Inserting...' : 'Insert to Page'}
                    </Button>

                    {inserted && (
                        <SectionMessage title="Success" appearance="success">
                            <Text>Report inserted into page!</Text>
                        </SectionMessage>
                    )}
                </Stack>
            </Stack>
        );
    }

    return (
        <Stack space="space.200">
            <Heading as="h3">Sprint Retro Report</Heading>
            <Text>Generate a sprint retrospective report.</Text>
            <Button
                appearance="primary"
                onClick={loadReport}
                isLoading={loading}
            >
                Generate Report
            </Button>
        </Stack>
    );
};

ForgeReconciler.render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
);
